# Generated by Django 4.2.3 on 2023-10-05 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_account_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='status',
        ),
        migrations.AlterField(
            model_name='account',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
