# Generated by Django 4.2.3 on 2023-10-05 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_remove_account_status_alter_account_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='profile_picture',
            field=models.FileField(default='some', upload_to='profile/'),
            preserve_default=False,
        ),
    ]
