# Generated by Django 4.2.3 on 2023-09-22 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100, verbose_name='categories')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=100)),
                ('uploaded_by', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='files/')),
                ('file_size', models.FloatField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TableFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accusor_name', models.CharField(max_length=255, verbose_name='ከሳሽ መልስ ሰጭ')),
                ('defendent_name', models.CharField(max_length=255, verbose_name='ተከሳሽ መልስ  ሰጭ')),
                ('house_number', models.CharField(max_length=255, verbose_name='የቤት ቁጥር')),
                ('id_number', models.CharField(max_length=255, verbose_name='የመ.ቁ ')),
                ('court_house', models.CharField(max_length=255, verbose_name='ክርክሩ የነበረበት ፍ/ቤት')),
                ('debate_type', models.CharField(max_length=255, verbose_name='የክርክሩ አይነት')),
                ('date_archive_initiated', models.DateTimeField(verbose_name='መዝገቡ የመጣበት ቀን')),
                ('date_court_decision_made', models.DateTimeField(verbose_name='ፍርድ ቤቱ ውሳኔ የሰጠበት ቀን')),
                ('date_court_decision_copy_sent', models.DateTimeField(verbose_name='የውሳኔ ግልባጭ የተላከበት ቀን')),
                ('status', models.CharField(max_length=255, verbose_name='በፍ/ቤቱ ውሳኔ መሰረት ተፈፅሞል/አልተፈፀመም')),
                ('prosecutor', models.CharField(max_length=255, verbose_name='ጉዳዩን የያዘው ዐቃቤ ህግ ስም')),
            ],
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder_name', models.CharField(max_length=256)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.category')),
            ],
        ),
    ]
