# Generated by Django 4.2.3 on 2023-09-25 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablefile',
            name='accusor_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ከሳሽ መልስ ሰጭ'),
        ),
        migrations.AlterField(
            model_name='tablefile',
            name='court_house',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ክርክሩ የነበረበት ፍ/ቤት'),
        ),
        migrations.AlterField(
            model_name='tablefile',
            name='date_archive_initiated',
            field=models.DateTimeField(blank=True, null=True, verbose_name='መዝገቡ የመጣበት ቀን'),
        ),
        migrations.AlterField(
            model_name='tablefile',
            name='date_court_decision_copy_sent',
            field=models.DateTimeField(blank=True, null=True, verbose_name='የውሳኔ ግልባጭ የተላከበት ቀን'),
        ),
        migrations.AlterField(
            model_name='tablefile',
            name='date_court_decision_made',
            field=models.DateTimeField(blank=True, null=True, verbose_name='ፍርድ ቤቱ ውሳኔ የሰጠበት ቀን'),
        ),
        migrations.AlterField(
            model_name='tablefile',
            name='debate_type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='የክርክሩ አይነት'),
        ),
        migrations.AlterField(
            model_name='tablefile',
            name='defendent_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ተከሳሽ መልስ  ሰጭ'),
        ),
        migrations.AlterField(
            model_name='tablefile',
            name='house_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='የቤት ቁጥር'),
        ),
        migrations.AlterField(
            model_name='tablefile',
            name='id_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='የመ.ቁ '),
        ),
        migrations.AlterField(
            model_name='tablefile',
            name='prosecutor',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ጉዳዩን የያዘው ዐቃቤ ህግ ስም'),
        ),
        migrations.AlterField(
            model_name='tablefile',
            name='status',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='በፍ/ቤቱ ውሳኔ መሰረት ተፈፅሞል/አልተፈፀመም'),
        ),
    ]
