# Generated by Django 4.2.3 on 2023-09-26 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_tablefile_accusor_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('uploaded_by', models.CharField(max_length=255)),
                ('action', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='recent/')),
                ('date_modified', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='tablefile',
            name='prosecutor',
            field=models.CharField(max_length=255, verbose_name='ጉዳዩን የያዘው ዐቃቤ ህግ ስም'),
        ),
    ]
