# Generated by Django 4.2.3 on 2023-09-26 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_activity_alter_tablefile_prosecutor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name': 'Activity', 'verbose_name_plural': 'Activities'},
        ),
        migrations.AddField(
            model_name='activity',
            name='modified_by',
            field=models.CharField(default='Ayalew', max_length=255),
            preserve_default=False,
        ),
    ]
