# Generated by Django 4.2.3 on 2023-09-18 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_delete_customuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='name',
            new_name='file_name',
        ),
        migrations.RemoveField(
            model_name='file',
            name='folder',
        ),
        migrations.AddField(
            model_name='file',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default='2023-03-12'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='file',
            name='file_size',
            field=models.FloatField(default=2.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='file',
            name='uploaded_by',
            field=models.CharField(default='solomon', max_length=255),
            preserve_default=False,
        ),
    ]
