# Generated by Django 4.2.3 on 2023-09-29 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_activity_edited_or_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accusor_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='ከሳሽ መልስ ሰጭ')),
                ('defendent_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='ተከሳሽ መልስ  ሰጭ')),
                ('house_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='የቤት ቁጥር')),
                ('id_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='የመ.ቁ ')),
                ('court_house', models.CharField(blank=True, max_length=255, null=True, verbose_name='ክርክሩ የነበረበት ፍ/ቤት')),
                ('debate_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='የክርክሩ አይነት')),
                ('date_archive_initiated', models.DateTimeField(blank=True, null=True, verbose_name='መዝገቡ የመጣበት ቀን')),
                ('date_court_decision_made', models.DateTimeField(blank=True, null=True, verbose_name='ፍርድ ቤቱ ውሳኔ የሰጠበት ቀን')),
                ('date_court_decision_copy_sent', models.DateTimeField(blank=True, null=True, verbose_name='የውሳኔ ግልባጭ የተላከበት ቀን')),
                ('prosecutor', models.CharField(max_length=255, verbose_name='ጉዳዩን የያዘው ዐቃቤ ህግ ስም')),
                ('status', models.CharField(blank=True, max_length=255, null=True, verbose_name='በፍ/ቤቱ ውሳኔ መሰረት ተፈፅሞል/አልተፈፀመም')),
                ('date_modified', models.DateTimeField(auto_now_add=True)),
                ('edited_or_deleted', models.CharField(max_length=255)),
                ('modified_by', models.CharField(max_length=255)),
            ],
        ),
    ]
