# Generated by Django 4.2.3 on 2023-09-29 13:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_recordactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activity',
            name='file_size',
            field=models.FloatField(default=12),
            preserve_default=False,
        ),
    ]
