# Generated by Django 4.2.3 on 2023-09-18 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_file_uploaded_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='uploaded_by',
            field=models.CharField(max_length=255),
        ),
    ]
